-- ============================================================================
-- Phase 2 数据库迁移脚本
-- PRO 订单与客户管理系统
-- 生成日期: 2026-06-09
-- 目标: PostgreSQL (timestamp without time zone)
-- ============================================================================

-- 注意: 所有变更兼容旧数据，添加默认值，可回滚

-- ============================================================================
-- 1. PaymentRecords 表变更
-- ============================================================================

-- 1a. 添加 CustomerId 列（不可空，兼容旧数据用 0 占位）
ALTER TABLE "PaymentRecords" 
ADD COLUMN IF NOT EXISTS "CustomerId" integer NOT NULL DEFAULT 0;

-- 1b. OrderId 改为可空（支持未绑定订单的预收款）
ALTER TABLE "PaymentRecords" 
ALTER COLUMN "OrderId" DROP NOT NULL;

-- 1c. 添加 AllocatedAmount（已核销金额）
ALTER TABLE "PaymentRecords" 
ADD COLUMN IF NOT EXISTS "AllocatedAmount" numeric NOT NULL DEFAULT 0;

-- 1d. 添加附件路径
ALTER TABLE "PaymentRecords" 
ADD COLUMN IF NOT EXISTS "AttachmentPaths" text;

-- 1e. 初始化已有记录的 CustomerId（从关联订单获取）
UPDATE "PaymentRecords" p
SET "CustomerId" = o."CustomerId"
FROM "Orders" o
WHERE p."OrderId" = o."Id" AND p."CustomerId" = 0;

-- 1f. 创建索引
CREATE INDEX IF NOT EXISTS "IX_PaymentRecords_CustomerId" ON "PaymentRecords" ("CustomerId");
CREATE INDEX IF NOT EXISTS "IX_PaymentRecords_CustomerId_PaymentDate" ON "PaymentRecords" ("CustomerId", "PaymentDate");

-- ============================================================================
-- 2. PaymentAllocations 新表（收款核销明细）
-- ============================================================================

CREATE TABLE IF NOT EXISTS "PaymentAllocations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PaymentRecordId" integer NOT NULL,
    "OrderId" integer NOT NULL,
    "Amount" numeric NOT NULL,
    "AllocatedById" integer NOT NULL,
    "Remark" text,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_PaymentAllocations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PaymentAllocations_PaymentRecords_PaymentRecordId" 
        FOREIGN KEY ("PaymentRecordId") REFERENCES "PaymentRecords"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PaymentAllocations_Orders_OrderId" 
        FOREIGN KEY ("OrderId") REFERENCES "Orders"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PaymentAllocations_Employees_AllocatedById" 
        FOREIGN KEY ("AllocatedById") REFERENCES "Employees"("Id")
);

CREATE INDEX IF NOT EXISTS "IX_PaymentAllocations_PaymentRecordId" ON "PaymentAllocations" ("PaymentRecordId");
CREATE INDEX IF NOT EXISTS "IX_PaymentAllocations_OrderId" ON "PaymentAllocations" ("OrderId");
CREATE INDEX IF NOT EXISTS "IX_PaymentAllocations_PaymentRecordId_OrderId" ON "PaymentAllocations" ("PaymentRecordId", "OrderId");

-- ============================================================================
-- 3. OrderStatusHistories 新表（订单状态变更历史）
-- ============================================================================

CREATE TABLE IF NOT EXISTS "OrderStatusHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "OrderNo" text NOT NULL DEFAULT '',
    "FromStatus" integer NOT NULL,
    "ToStatus" integer NOT NULL,
    "Reason" text NOT NULL DEFAULT '',
    "OperatorId" integer NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_OrderStatusHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderStatusHistories_Orders_OrderId" 
        FOREIGN KEY ("OrderId") REFERENCES "Orders"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrderStatusHistories_Employees_OperatorId" 
        FOREIGN KEY ("OperatorId") REFERENCES "Employees"("Id")
);

CREATE INDEX IF NOT EXISTS "IX_OrderStatusHistories_OrderId" ON "OrderStatusHistories" ("OrderId");
CREATE INDEX IF NOT EXISTS "IX_OrderStatusHistories_CreatedAt" ON "OrderStatusHistories" ("CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_OrderStatusHistories_OrderId_CreatedAt" ON "OrderStatusHistories" ("OrderId", "CreatedAt");

-- ============================================================================
-- 4. PaymentStatusHistories 新表（收款状态变更历史）
-- ============================================================================

CREATE TABLE IF NOT EXISTS "PaymentStatusHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EntityType" text NOT NULL DEFAULT '',
    "EntityId" integer NOT NULL,
    "FromStatus" integer NOT NULL,
    "ToStatus" integer NOT NULL,
    "Reason" text NOT NULL DEFAULT '',
    "OperatorId" integer NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_PaymentStatusHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PaymentStatusHistories_Employees_OperatorId" 
        FOREIGN KEY ("OperatorId") REFERENCES "Employees"("Id")
);

CREATE INDEX IF NOT EXISTS "IX_PaymentStatusHistories_EntityType_EntityId" ON "PaymentStatusHistories" ("EntityType", "EntityId");
CREATE INDEX IF NOT EXISTS "IX_PaymentStatusHistories_CreatedAt" ON "PaymentStatusHistories" ("CreatedAt");

-- ============================================================================
-- 5. AuditLogDetails 新表（审计日志详情 - 前后值对比）
-- ============================================================================

CREATE TABLE IF NOT EXISTS "AuditLogDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EntityType" text NOT NULL DEFAULT '',
    "EntityId" integer NOT NULL,
    "EntityName" text NOT NULL DEFAULT '',
    "FieldName" text NOT NULL DEFAULT '',
    "OldValue" text,
    "NewValue" text,
    "ActionType" text NOT NULL DEFAULT '',
    "Reason" text NOT NULL DEFAULT '',
    "OperatorId" integer NOT NULL,
    "BranchId" integer NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_AuditLogDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AuditLogDetails_Employees_OperatorId" 
        FOREIGN KEY ("OperatorId") REFERENCES "Employees"("Id")
);

CREATE INDEX IF NOT EXISTS "IX_AuditLogDetails_EntityType_EntityId" ON "AuditLogDetails" ("EntityType", "EntityId");
CREATE INDEX IF NOT EXISTS "IX_AuditLogDetails_ActionType" ON "AuditLogDetails" ("ActionType");
CREATE INDEX IF NOT EXISTS "IX_AuditLogDetails_OperatorId" ON "AuditLogDetails" ("OperatorId");
CREATE INDEX IF NOT EXISTS "IX_AuditLogDetails_BranchId" ON "AuditLogDetails" ("BranchId");
CREATE INDEX IF NOT EXISTS "IX_AuditLogDetails_CreatedAt" ON "AuditLogDetails" ("CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_AuditLogDetails_EntityType_FieldName_CreatedAt" ON "AuditLogDetails" ("EntityType", "FieldName", "CreatedAt");

-- ============================================================================
-- 回滚脚本（如需回退）
-- ============================================================================
/*
-- 删除新表
DROP TABLE IF EXISTS "AuditLogDetails";
DROP TABLE IF EXISTS "PaymentStatusHistories";
DROP TABLE IF EXISTS "OrderStatusHistories";
DROP TABLE IF EXISTS "PaymentAllocations";

-- 恢复 PaymentRecords 表
ALTER TABLE "PaymentRecords" DROP COLUMN IF EXISTS "AttachmentPaths";
ALTER TABLE "PaymentRecords" DROP COLUMN IF EXISTS "AllocatedAmount";
ALTER TABLE "PaymentRecords" ALTER COLUMN "OrderId" SET NOT NULL;
ALTER TABLE "PaymentRecords" DROP COLUMN IF EXISTS "CustomerId";
DROP INDEX IF EXISTS "IX_PaymentRecords_CustomerId";
DROP INDEX IF EXISTS "IX_PaymentRecords_CustomerId_PaymentDate";
*/
